import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#333333',
    paddingTop: 16,
    paddingBottom: 36,
    paddingHorizontal: 30,
    lineHeight: 1.5,
  },
  author: { textAlign: 'center', marginBottom: 8 },
  name: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    letterSpacing: 1.5,
    color: '#1A0000',
    marginBottom: 4,
  },
  roleTitle: {
    fontSize: 11,
    color: '#333333',
    marginTop: 12,
    letterSpacing: 0.5,
    fontWeight: 'bold',
    textTransform: 'capitalize',
  },
  contact: { textAlign: 'center', marginBottom: 4, fontSize: 10 },
  contactLine: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: 4,
  },
  contactLinks: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  link: {
    color: '#0b3d91',
    textDecoration: 'underline',
    marginHorizontal: 8,
  },
  separator: { color: '#333333', marginHorizontal: 6 },
  sectionTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    textTransform: 'uppercase',
    color: '#1A0000',
    marginTop: 4,
    marginBottom: 4,
  },
  summary: { fontSize: 10, color: '#1A202C', marginBottom: 0 },
  hr: {
    borderBottomWidth: 1,
    borderBottomColor: '#cccccc',
    marginVertical: 4,
  },
  jobHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
    marginTop: 4,
  },
  experienceTitle: {
    fontSize: 10.5,
    fontFamily: 'Helvetica-Bold',
    color: '#1A0000',
    flex: 1,
    paddingRight: 8,
  },
  jobMeta: { fontSize: 9, color: '#333333' },
  bulletRow: { flexDirection: 'row', marginBottom: 2, paddingLeft: 5 },
  bullet: { width: 10, fontSize: 10 },
  bulletText: { flex: 1, fontSize: 10, color: '#1A202C' },
  skillRow: { flexDirection: 'row', marginBottom: 2 },
  skillLabel: {
    width: 120,
    fontSize: 9.5,
    fontFamily: 'Helvetica-Bold',
    color: '#1A0000',
  },
  skillItems: { flex: 1, fontSize: 10, color: '#1A202C' },
  eduHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 3,
  },
  degree: {
    fontSize: 10.5,
    fontFamily: 'Helvetica-Bold',
    color: '#1A0000',
  },
  eduDate: { fontSize: 9, color: '#333333' },
  university: { fontSize: 10, color: '#333333' },
  additionalRow: { flexDirection: 'row', marginBottom: 5 },
  additionalLabel: {
    width: 120,
    fontSize: 9.5,
    fontFamily: 'Helvetica-Bold',
    color: '#1A0000',
  },
  additionalValue: { flex: 1, fontSize: 10, color: '#1A202C' },
});
